### PR TITLE
Mocks and Utils

### PR DESCRIPTION
**Pull request by kamilkisiela**
@helfer Continuation of #1

### CODE REVIEW

**Comment by kamilkisiela** [comment]
And an example of usage https://github.com/apollographql/apollo-angular/pull/278/files

**Comment by kamilkisiela** [comment]
I think it's ready

**Comment by helfer** [comment]
Awesome! @kamilkisiela @linonetwo can one of you write a nice README.md for the repo?

**Comment by helfer** [comment]
Merged. Someone will have to write a `readme` some other time.

**Pull request merged**
