### PR TITLE
Immigrate mocks, utils and tests to standalone repo

### PR DESCRIPTION
**Pull request by linonetwo**
With some lint

### CODE REVIEW

**Comment by kamilkisiela** [comment]
@linonetwo why `karma`? There's no usage of this

**Comment by linonetwo** [comment]
@kamilkisiela  I move some test from apollo-client to here, making sure that I didn't made anything wrong.

It is a devDependencies, I think it's OK.

**Comment by linonetwo** [comment]
I believe it's OK to merge, most of the tests passed.

**Comment by helfer** [comment]
@linonetwo what is Karma used for? I think it may be better to have the same testing setup as in all other repositories, because it will make it easier for people to work across repos.

**Comment by linonetwo** [comment]
@helfer I get it, other repo just use mocha.

I use karma because some tests said fetch is not defined, which comes from apollo-client, so I thought using mocha can avoid that.

**Comment by linonetwo** [comment]
@kamilkisiela  I don't know how to deal with this:

```
node_modules/.3.4.34@@types/chai/index.d.ts(399,18): error TS2300: Duplicate identifier 'AssertionError'.
node_modules/.3.4.34@@types/chai/index.d.ts(411,5): error TS2300: Duplicate identifier 'export='.
node_modules/@types/chai/index.d.ts(399,18): error TS2300: Duplicate identifier 'AssertionError'.
node_modules/@types/chai/index.d.ts(411,5): error TS2300: Duplicate identifier 'export='.
```

**Comment by kamilkisiela** [comment]
if `fetch` is not defined then you should use some polyfill, `isomorphic-fetch` for example :) this should fix the issue.

**Comment by kamilkisiela** [comment]
@linonetwo about your issue with `@types/chai`, everything works for me.

I don't know why you have `node_modules/.3.4.34`... Try to remove `node_modules` and do `npm install`

**Comment by linonetwo** [comment]
@kamilkisiela Seems node_modules/.3.4.34 is from cnpm, a chinese accelerated npm. Using npm i I successfully get rid of it.

Now all tests passed.

Some unrelated tests are still there, I can clean it up later.

**Comment by linonetwo** [comment]
@kamilkisiela Take a look ~ What else can I do for you?

**Comment by kamilkisiela** [comment]
@linonetwo Hi :))

You can do few things

remove:
- brfs
- browserify
- typed-graphql
- watchify

update `apollo-client` to ^0.7.1

This way we can tell if it works with the latest version

**Comment by kamilkisiela** [comment]
@helfer Do you think it could be merged?

**Comment by linonetwo** [comment]
How to dealwith:
```
> tsc

error TS2688: Cannot find type definition file for 'node'.
```

My tsconfig is:
```
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["es6", "dom"],
    "types": [
      "node",
      "mocha",
      "chai"
    ],
    "module": "commonjs",
    "moduleResolution": "node",
    "removeComments": true,
    "sourceMap": true,
    "declaration": true,
    "rootDir": ".",
    "outDir": "dist",
    "noImplicitAny": false
  },
  "files": [
    "typings.d.ts",
    "src/index.ts",
    "tests/index.ts"
  ]
}
```

**Comment by kamilkisiela** [comment]
You need to install @types/node

czw., 12 sty 2017, 14:22 użytkownik lin onetwo <notifications@github.com>
napisał:

**Comment by linonetwo** [comment]
This time, it full of errors likes ```error TS2307: Cannot find module 'apollo-client/transport/networkInterface'.```

Do I need to install anything or configure anything?

**Comment by kamilkisiela** [comment]
Just change it to `apollo-client/lib/src/transport/networkInterface`.

**Comment by linonetwo** [comment]
Well, It's a little outdated, I need more time to fix.

**Comment by recidive** [comment]
Hello guys, this is really great thing. We are looking after this to help with our Apollo client tests.

Let me know how I could help.

**Comment by recidive** [comment]
Shouldn't we migrate only the test helpers here?

**Comment by sebas5384** [comment]
Test utils, yeah!! really need this to do our tests, how can I help :)

**Comment by kamilkisiela** [comment]
@recidive yes, definitely.

I updated dependencies and fixed all the issues to make code from `src/*` working. Take a look at [my commit](https://github.com/apollographql/apollo-test-utils/commit/5a4a7558bcb832cba4d7897a21ddc3a83ad9ad67).

@sebas5384 @recidive You can try to remove unnecessary tests and create / leave only those related to mockups and utils from `/src`.

**Comment by kamilkisiela** [comment]
[Apollo Contributor Week](https://dev-blog.apollodata.com/save-the-date-apollo-contributor-week-eef66d09f0e6#.58tca6tyo) is coming soon but you can already help if you want to :) You can reach me on apollo's slack channel (same user handle as on github).

**Comment by helfer** [comment]
@kamilkisiela let's get this moving again! How can I help?

**Comment by helfer** [comment]
Nvm, just saw what's going on. I'll close this PR and merge #4 which is a continuation of it :)

**Pull request closed without merging**
